title: QBI-Software
description: Custom Software Services and Resources for QBI, The University of Queensland
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
